is_simulation: false
elisa_station: true
register_time: 2.0


N_agents: 2
l: 2
network_gain:
  - 1.0
  - 1.0
sampling_rate: 100
lambda: 1.0
gamma: 1.0

output: z

formation:
  type: consensus
# formation:
#   type: circle
#   radius: 0.2

