is_simulation: false
elisa_station: true
register_time: 2.0


N_agents: 2
l: 2
network_gain:
  - 1.5
  - 1.5
sampling_rate: 100
lambda: 1.0
gamma: 3.0
kappa: 0.0

output: r

# formation:
#   type: line
#   spacing: 0.3
formation:
  type: consensus
# formation:
#   type: circle
#   radius: 0.2

