
NF:
  alpha: 35
  gamma:
    r_w: 30 #1.5
    eps: 0.0004 #0.00001 #0.005 #0.17
  beta:
    function:
      R: 0.1
      delta: 0.05 # bigger means less steep -> less chance of divergence.

    # robot base, make z ref higher! -> Since coop of panda is also x,y it is now trying to evade the cylinder around its base... 
    #The z coordinate does not matter!
    # obstacle_0:
    #   type: obstacle
    #   radius: 0.12
    #   location:
    #     - 0.0
    #     - 0.0
    #     - 0.0

    # y axis bound on the workspace
    obstacle_0:
      type: lower_bound_x
      value: -0.66 #-0.56

    # y axis bound on the workspace
    obstacle_1:
      type: lower_bound_y
      value: -0.66 #-0.56
