is_simulation: false
elisa_station: true
register_time: 1.0

N_agents: 2
l: 2
network_gain:
  - 2.0
  - 2.0
sampling_rate: 100
lambda: 1.0
gamma: 6.0
kappa: 3.0

output: z

formation:
  type: consensus

# elisa_0:
#   ID: 0
#   marker_id: 10
#   address: 3658
#   color: blue

# elisa_1:
#   ID: 1
#   marker_id: 6
#   address: 3656
#   color: orange