is_simulation: true
register_time: 2.0
elisa_station: false

network:
  enabled: true
  delay: 0.2

N_agents: 2
l: 5
sampling_rate: 100
network_gain:
  - 3.0
  - 3.0
  - 3.0
  - 3.0
  - 3.0
lambda: 1.0
gamma: 3.0

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.7
    - 0.0
    - -3.0
  gain:
    - 0.0
    - 0.0
    - 3.0
    - 5.0
    - 5.0 # Psi does not correspond to my definition of z?

output: r

connectedpandasim:
  type: panda/ConnectedPandasim

formation:
  type: consensus

# formation:
#   type: manual
#   position_0:
#     - 0.0
#     - 0.0
#     - 0.7
#   position_1:
#     - 0.0
#     - 0.0
#     - 0.0