is_simulation: true

N_agents: 2
l: 3
sampling_rate: 100
network_gain:
  - 3.0
  - 3.0
  - 3.0
lambda: 1.0
gamma: 3.0

output: r

connectedpandasim:
  type: panda/ConnectedPandasim

formation:
  type: manual
  position_0:
    - 0.0
    - 0.0
    - 0.7
  position_1:
    - 0.0
    - 0.0
    - 0.0