N_agents: 2
l: 3
network_gain:
  - 15.0
  - 15.0
  - 15.0
lambda: 14.0

controller:
  kq: 1.0
  kz: 3.0
  gravity_compensation:
    enabled: true
  local_potential:
    enabled: false
    gains:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    goals:
    - 0.0
    - 0.2
    - 0.0
    - 0.15
    - 0.0
    - 0.0
    - 0.0
  joint_limit_avoidance:
    enabled: true 
    gains:
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    - 0.25
    limits_min: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]
    limits_max: [2.8973, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973]
  integral:
    enabled: false
    gain: 
      - 0.9
      - 0.9
      - 0.9
    saturation: 3.0
    torque_enable: 3.0
  wang:
    Rw: 1.0
    eps: 0.1
    

panda:
  type: panda/Panda
  joint_names:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
  arm_id: panda
  vel_max: 0.05
  z_lower_bound: 0.3
  velocity_element_bound: 1.5
  velocity_norm_bound: 0.3
  torque_bound: 6.0
  alpha: 0.99
  ID: 0

beacon:
  ID: 1
  goal_type: 1

  