is_simulation: true
register_time: 4.0

N_agents: 2
l: 3
sampling_rate: 100
network_gain:
  - 3.0
  - 3.0
  - 3.0
lambda: 1.0
gamma: 1.0
kappa: 1.0

output: r
# leader:
#   id: 0
#   gain:
#     - 3.0
#     - 3.0
#     - 8.0
#   ref:
#     - 0.0
#     - 0.0
#     - 0.6

formation:
  type: consensus

panda:
  type: panda/Panda
