is_simulation: false
register_time: 5.0
elisa_station: true

sampling_rate: 100
N_agents: 3
# elisa:
#   elisa_0: 3658
l: 3
network_gain:
  - 1.0
  - 1.0
  - 1.0
lambda: 1.0
gamma: 1.0
kappa: 1.0

output: r

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.4
  gain:
    - 0.0
    - 0.0
    - 1.0
# Normalise!

formation:
  type: circle
  radius: 0.1
  phase: 1.67

# formation:
#   type: line
#   spacing: 0.15
#   phase: 1.67

# formation:
#   type: consensus

panda:
  type: panda/Panda