is_simulation: false
register_time: 4.5
elisa_station: true

sampling_rate: 100
N_agents: 3
# elisa:
#   elisa_0: 3658
l: 3
network_gain:
  - 1.5
  - 1.5
  - 1.5
lambda: 1.0
gamma: 1.0
kappa: 0.3

output: r

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.5
  gain:
    - 0.0
    - 0.0
    - 6.0
# Normalise!

# formation:
#   type: circle
#   radius: 0.06

formation:
  type: line
  spacing: 0.15
  phase: 0.0

# formation:
#   type: consensus

panda:
  type: panda/Panda