is_simulation: false
register_time: 2.0

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 3.0
  - 3.0
  - 3.0 #3.0
lambda: 1.0
gamma: 3.0

output: r

formation:
  type: consensus

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.6
  gain:
    - 0.0
    - 0.0
    - 8.0
# formation:
#   type: manual
#   position_0:
#     - 0.0
#     - 0.0
#     - 0.7
#   position_1:
#     - 0.0
#     - 0.0
#     - 0.0

panda:
  type: panda/Panda