is_simulation: false

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 3.0
  - 3.0
  - 3.0 #3.0
lambda: 1.0
gamma: 3.0

output: r

formation:
  type: manual
  position_0:
    - 0.0
    - 0.0
    - 0.7
  position_1:
    - 0.0
    - 0.0
    - 0.0

panda:
  type: panda/Panda