is_simulation: false
register_time: 2.0

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 1.0 
  - 1.0
  - 1.0 #4.0
lambda: 1.0
gamma: 1.0
kappa: 1.0
eta: 0.01

output: r

panda:
  type: panda/Panda

formation:
  type: consensus