is_simulation: false
register_time: 2.0

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 4.0
  - 4.0
  - 4.0 #3.0
lambda: 1.0
gamma: 0.5
kappa: 1.0

output: r

panda:
  type: panda/Panda

formation:
  type: consensus