is_simulation: false
register_time: 2.0

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 20.0 
  - 20.0
  - 20.0 #4.0
lambda: 1.0
gamma: 2.0
kappa: 0.01

output: r

panda:
  type: panda/Panda

formation:
  type: consensus