N_agents: 2
l: 3
network_gain: 5.0
lambda: 5.0

controller:
  gravity_compensation:
    enabled: false
  local_potential:
    enabled: false
    gains:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    goals:
    - 0.0
    - 0.2
    - 0.0
    - 0.15
    - 0.0
    - 0.0
    - 0.0
  joint_limit_avoidance:
    enabled: false 
    gains:
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    - 0.1
    limits_min: [-2.8973, -1.7628, -2.8973, -3.0718, -2.8973, -0.0175, -2.8973]
    limits_max: [2.8973, 1.7628, 2.8973, -0.0698, 2.8973, 3.7525, 2.8973]
  kv: 0.01
  integral:
    enabled: false
    gain: 1.0

    

panda:
  type: panda/Panda
  joint_names:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
  arm_id: panda
  vel_max: 0.05
  z_lower_bound: 0.15
  velocity_element_bound: 1.5
  velocity_norm_bound: 0.3
  torque_bound: 10.0
  ID: 0

beacon:
  ID: 1
  goal:
    - 0.1
    - 0.4
    - 0.8

  