N_agents: 1

net_gain: 1.0

controller:
  Vs_gains:
  - 1.0
  - 3.0
  - 0.0
  - 1.0
  - 0.0
  - 0.0
  - 0.0
  theta_star:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  l: 3



panda:
  type: panda/Panda
  joint_names:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
  arm_id: panda
  vel_max: 0.05
  z_lower_bound: 0.4
  velocity_element_bound: 0.5
  velocity_norm_bound: 0.3
  torque_bound: 6.0
  