is_simulation: false
register_time: 4.5
elisa_station: true

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 3.0
  - 3.0
  - 3.0
lambda: 1.0
gamma: 1.0
kappa: 1.0

output: r

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.7
  gain:
    - 0.0
    - 0.0
    - 8.0
# Normalise!

formation:
  type: consensus

panda:
  type: panda/Panda