is_simulation: false
register_time: 0.5
elisa_station: true

sampling_rate: 100
N_agents: 2
l: 1
network_gain:
  - 3.0
lambda: 1.0
gamma: 3.0

output: r

formation:
  type: consensus

panda:
  type: panda/Panda