is_simulation: false
register_time: 0.5
elisa_station: true

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 4.0
  - 4.0
  - 4.0
lambda: 1.0
gamma: 3.0

output: r

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.5
  gain:
    - 0.0
    - 0.0
    - 8.0

formation:
  type: consensus

panda:
  type: panda/Panda