is_simulation: false
register_time: 5.0
elisa_station: true

sampling_rate: 100
N_agents: 2
l: 3
network_gain:
  - 2.5
  - 2.5
  - 2.5
lambda: 1.0
gamma: 7.0
kappa: 0.5

output: r

leader:
  id: 0
  ref: 
    - 0.0
    - 0.0
    - 0.3
  gain:
    - 0.0
    - 0.0
    - 1.0
# Normalise!

formation:
  type: consensus

panda:
  type: panda/Panda