is_simulation: true
register_time: 2.0
elisa_station: false

N_agents: 2
l: 2
sampling_rate: 100
network_gain:
  - 3.0
  - 3.0
lambda: 1.0
gamma: 3.0

output: r

connectedpandasim:
  type: panda/ConnectedPandasim

formation:
  type: consensus

# formation:
#   type: manual
#   position_0:
#     - 0.0
#     - 0.0
#     - 0.7
#   position_1:
#     - 0.0
#     - 0.0
#     - 0.0